sudo: required
services:
  - docker

before_install:
  - docker build -t cjarvis88/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cjarvis88/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-299307012230"
  bucket_path: "docker-react"
  on:
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY